config/routes.rb
Rails.application.routes.draw do

  root 'home#gossip'

  get 'home', to:'home#home'

  get 'home/:gossip_id', to:'home#show_gossip'

  get 'static/team', to: 'static#team'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'static/contact', to:'static#contact'

  get'bienvenue/show', to:'bienvenue#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  # 1-N associations with user
  belongs_to :user

  # 1-N polymorphic association with comment and gossip
  belongs_to :commentable, polymorphic: true # can be associated to anything commentable
  has_many :comments, as: :commentable # is something commentable

  # 1-N associations with likes
  has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
	has_many :tags
end

app/models/gossip_metum.rb
class GossipMetum < ApplicationRecord
	#1-N association with gossip taable
	belongs_to :gossip

	#1-N association with tags table
	belongs_to :tags
end

app/models/like.rb
class Like < ApplicationRecord

  # 1-N associations with users, gossips and comments
  belongs_to :user
  # can apply to a gossip or a comment
  belongs_to :gossip, optional: true if :comment_id
  belongs_to :comment, optional: true if :gossip_id

end

app/models/message_delivering.rb
class MessageDelivering < ApplicationRecord

  # 1-N association with recipients (users) table
  # class_name tells rails recipient is a user
  belongs_to :recipient, class_name: 'User'

  # 1-N association with received_messages (private_messages) table
  # class_name tells rails received_message is a private_message
  belongs_to :received_message, class_name: 'PrivateMessage'

end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User", required: false
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :gossips, through: :gossip_meta
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :city
	has_many :gossips
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bienvenue_controller.rb
class BienvenueController < ApplicationController


  def index_post

  	puts "Hello depuis le serveur"
  	user = User.new
  	user.first_name = params["first_name"]
  	user.save
  	puts "c'est fini !"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def gossip
  	@all_gossips = []
    @all_gossips= Gossip.all
  end

  def show_gossip

    @gossip = Gossip.find(params[:user_id])
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def team
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bienvenue_helper.rb
module BienvenueHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/bienvenue/show.html.erb
<h1>Bienvenue#show</h1>


<form action ="/" method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
	<input type="text" name="first_name">
	<input type="submit" name="Envoyer">
<p>Salut à toi <%= @user.first_name%></p>

app/views/home/home.html.erb
<html>
  <head>
    <title>The Gossip Project</title>
  </head>
  <body>
    <h1>Bienvenue à toi !!! Moussaille friand de potins...</h1> 

    <% Gossip.all.each_with_index do |gossip, index| %>
        <p>
          <%= gossip.user_id %><br/>
          <%= gossip.title %><br/>
          <a href="/home/<%= @user_id %>">POTIN</a>
        </p>
      <% end %>

  </body>
</html>

app/views/home/show_gossip.html.erb
<h2>PAGE POTIN !</h2>

  <p> Voici le potin n° <%= @gossip.id%><br/>
  Son auteur : <%= @gossip.user.last_name %><br/>
  Le titre : <%= @gossip.title %><br/>
  Créé le : <%= @gossip.created_at.strftime('%d/%m/%Y') %><br/>
  Le contenu du potin : <%= @gossip.content %>
  </p>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>TheGrosSlipProJet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

<body>

    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-info">
      <a class="navbar-brand" > <%= link_to "Gossip", home_path, class: "nav-link" %> 
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">



            <li class="nav-item">
            <%= link_to "Team", static_team_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Contact", static_contact_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
    </nav>

    <%= yield %>
    
  </body>
</html>